### ISSUE TITLE
No timeout in CURL call

### ISSUE THREAD

**Issue by afdaniele** [duckietown/duckietown-shell#12]
https://github.com/duckietown/duckietown-shell/blob/5c10e1538f43ca62bad8bf3a24aca10c6d3541b0/lib/dt_shell/version_check.py#L36

This call to `curl` does not appear to have a timeout specified. I was running the shell with no internet and the program hanged for at least 10 seconds. I killed after that and saw that the program was stuck at this line. Is this lack of timeout intended?

**Comment by AndreaCensi** [comment]
@afdaniele  are you using Mac?

The curl fallback is because urllib2 on Mac has problems with https.

**Comment by AndreaCensi** [comment]
For the timeout, yes there should be one.

**Comment by afdaniele** [comment]
@AndreaCensi , I hit the issue with https on Mac as well. I use `requests` instead. Check here: https://github.com/duckietown/duckietown-shell/blob/13ed1a4fd9ea4ce8001e92577d45c9766022eeec/lib/dt_shell/cli.py#L156.
