### ISSUE TITLE
Clearer Installation Instructions

### ISSUE THREAD

**Issue by takeitallsource** [duckietown/duckietown-shell#19]
@AndreaCensi would it be worth it to clarify that the command `pip2 install --no-cache-dir -U duckietown-shell` should occur inside the `dts` virtual environment.

I'm not sure if it is just my issue but I felt a bit of disconnection between the virtual env creation and the posterior instructions that may lead to some problems.

I can create PR for that.

**Comment by AndreaCensi** [comment]
I did not put the virtualenv instructions.

Yes please go ahead.

But note that this is not really necessary.
