### ISSUE TITLE
see readme without scrolling

### ISSUE THREAD

**Issue by bowser101** [duckietown/duckietown-shell#27]
it would be more user friendly to be able to see the readme immediately (instead of scrolling down) when you get tot the instructions from the AIDO manual.
can you adjust githubs page layout?

![image](https://user-images.githubusercontent.com/16885037/46906172-55543680-cecd-11e8-912e-d35f8c5e0ccb.png)

![image](https://user-images.githubusercontent.com/16885037/46906186-90ef0080-cecd-11e8-8dc7-eb3fe7e78796.png)
I see this and panic - what am I supposed to do now!

**Comment by AndreaCensi** [comment]
No but we could link to the README.md directly

**Comment by liampaull** [comment]
downside is that it becomes branch specific, let's leave it as is and add a note to scroll down
