### ISSUE TITLE
dts challenges evaluate leads to Error

### ISSUE THREAD

**Issue by bhairavmehta95** [duckietown/duckietown-shell#29]
Upon running `dts challenges evaluate` to run the new local evaluation, when running the `pip install -r requirements.txt` command, I am always getting:

`ERROR:dts:UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.`

Will debug and update the issue if I find something.

**Comment by AndreaCensi** [comment]
Which challenge/template?

**Comment by bhairavmehta95** [comment]
AIDO1_LF1, The ROS Template.

The error usually occurs when its pulling the evaluation container though.

https://github.com/duckietown/challenge-aido1_LF1-template-ros/tree/ros-initial

**Comment by bhairavmehta95** [comment]
Closing because upon closer inspection, it just seems to be due to the speed of some installation steps when using the `qemu3-arm-static` entrypoint. Took ~1 hour to get the thing running - so while its not an error, hopefully we can do something to make it faster.
