### ISSUE TITLE
dts commands become to failed..

### ISSUE THREAD

**Issue by FUJI-AF** [duckietown/duckietown-shell#42]
![screenshot from 2019-02-19 12-04-45](https://user-images.githubusercontent.com/47373222/52988652-6f85be80-3443-11e9-8c77-0a254cbe9c7d.png)

any dts commands become to failed....

**Comment by liampaull** [comment]
this is a problem with your Docker configuration. what dts shell command are you running? One possibility is that in a previous step you have set `export DOCKER_HOST=![duckiebot_name]` and now it is trying to run Docker commands on the duckiebot that should be run on the laptop. For this I prefer to manually specify the host where the Docker commands should be run:

    $ docker -H ![duckiebot_name].local ....

**Comment by FUJI-AF** [comment]
![screenshot from 2019-02-20 17-10-12](https://user-images.githubusercontent.com/47373222/53076198-750e0200-3532-11e9-8b21-271c4ddbb969.png)
![screenshot from 2019-02-20 17-10-21](https://user-images.githubusercontent.com/47373222/53076206-7a6b4c80-3532-11e9-8595-9dd51f98f9a0.png)

I tried this commands.

**Comment by liampaull** [comment]
I think Docker is either not installed correctly or not the daemon is not running on our laptop. 

Can you try 

    $ unset DOCKER_HOST
    $ docker ps

and put the output here?

**Comment by liampaull** [comment]
Also note that you have to add your user to the docker group and then log out and log back in as described in [Sec. 1.3 here](http://docs.duckietown.org/DT18/opmanual_duckiebot/out/laptop_setup.html)

**Comment by FUJI-AF** [comment]
1.3-(3) 
Does `'whoami'` need to change?

**Comment by FUJI-AF** [comment]
The docker was masked and it was not working.
Docker is started service.

But

`dts duckiebot keyboard_control <hostname>` is executed and the window pops up, but the motor does not move even if you press the arrow key.

**Comment by FUJI-AF** [comment]
motor pin confirmed.

**Comment by FUJI-AF** [comment]
The docker was masked and it was not working.
Docker is started service.

But

`dts duckiebot keyboard_control <hostname>` is executed and the window pops up, but the motor does not move even if I press the arrow key.

**Comment by FUJI-AF** [comment]
`$ docker -H hostname.local run -dit --privileged --name joystick --network=host -v /data:/data duckietown/rpi-duckiebot-joystick-demo:master18`
This container I removed. and put again.　Then the motor moved.

**Comment by FUJI-AF** [comment]
![screenshot from 2019-02-27 17-40-45](https://user-images.githubusercontent.com/47373222/53476921-e14eaf80-3ab6-11e9-9c1d-211c02e17c61.png)
An error occurs in motor calibration.

What value should be entered for trim value?
Also, what are the upper and lower limits of it?

**Comment by liampaull** [comment]
the service should be available if things are running properly. Can you run 

    $ rosservice list

and post the output?

**Comment by FUJI-AF** [comment]
![screenshot from 2019-02-28 17-12-12](https://user-images.githubusercontent.com/47373222/53551209-12dd7e80-3b7c-11e9-8953-ad699a8e216e.png)
Thank you for the reply.
This is output.

**Comment by FUJI-AF** [comment]
I closed issue by mistake.
