### ISSUE TITLE
Can't set token: AttributeError: 'DTShell' object has no attribute 'config'

### ISSUE THREAD

**Issue by KobeLeenders** [duckietown/duckietown-shell#54]
Every time I try to set my token I get this error, the token is valid and I get the same type of error if I type 'dts update'. I've tried reinstalling dts, docker, other tokens and even my whole operating system but I can't seem to find a solution.
I run dts on ubuntu 18.04

![Screenshot from 2019-10-12 20-51-43](https://user-images.githubusercontent.com/32452483/66706393-38498200-ed32-11e9-97be-42a2180627d0.png)
![Screenshot from 2019-10-12 20-52-25](https://user-images.githubusercontent.com/32452483/66706394-38498200-ed32-11e9-8db9-b7314aa25a83.png)

**Comment by afdaniele** [comment]
@KobeLeenders It is fixed now, try again.
