### ISSUE TITLE
Duckiebot won't flash

### ISSUE THREAD

**Issue by HumbletNicky** [duckietown/duckietown-shell#55]
When trying to flash the SD-card  I run into the following error:

![1](https://user-images.githubusercontent.com/33546666/67099058-8987c480-f1bd-11e9-90cd-cd7380b8d2d5.png)
![2](https://user-images.githubusercontent.com/33546666/67099071-8db3e200-f1bd-11e9-960e-76aaec7804da.png)
![3](https://user-images.githubusercontent.com/33546666/67099074-90163c00-f1bd-11e9-8377-7fdbe90cafae.png)

**Comment by afdaniele** [comment]
This was due to non-English terminals. It has been fixed. Closing.
