### ISSUE TITLE
SD card not found 

### ISSUE THREAD

**Issue by asal97** [duckietown/duckietown-shell#86]
Hi, I am trying to run init on my sd card
`dts init_sd_card --hostname duck1 --type duckiebot --configuration DB21M --wifi uit-byod:wifibyod`
when it comes to choosing the the right drive to flash it prints that no devices were found with the size of my sd card.
however i can see that my pc recognizes it since it is showing in my drives!

**Comment by afdaniele** [comment]
Try adding `-S 32` to your command if you are using a 32GB SD card.

**Comment by asal97** [comment]
it still prints that 
**No devices were found with a size of ~64GB.**

I have done these steps to add the sd card to the wsl :
1. PowerShell as admin:
wsl --update
winget install --interactive --exact dorssel.usbipd-win
usbipd wsl list
usbipd wsl attach --busid <busid>

2. WSL2:
sudo apt update
sudo apt upgrade
sudo adduser <user> dialout
sudo apt install linux-tools-5.4.0-77-generic hwdata

Now while running `lsusb` i can see the sd card in my attached list but still doesn't show up while running init_sd_card

**Comment by bolapoules** [comment]
What's the status on this issue? What is the current working approach on burning the image on an sd-reader from wsl? `usbipd` will show under `lsusb` but nothin is under `/dev/`.
