### ISSUE TITLE
`dts code editor` fails on 22.04

### ISSUE THREAD

**Issue by sjev** [duckietown/duckietown-shell#90]
**symptom** 
The editor fails to start with dts code editor complaining about

     
      :    File "/home/jev/.dt-shell/commands-multi/daffy/code/editor/command.py", line 44, in command
      :      default=os.getlogin(),
      :  OSError: [Errno 6] No such device or address

**info**
It's not a specific dts  issue though, as os.getlogin() run in ipython throws the same error.  

contents of shell-debug-info.txt :

 commands-version: daffy
dt-authentication-daffy: 0.1.16
dt-data-api-daffy: 1.1.3
duckietown-docker-utils-daffy: 6.1.1
duckietown-shell: 5.4.3
duckietown-shell-commands: 5.4.5
encodings:
  locale: UTF-8
  stderr: utf-8
  stdout: utf-8
python: 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]

This happens on Ubuntu 22.04.1 LTS

**how to reproduce**

I've built a docker container based on 22.04:

1. shell into container `docker run -it sjev/duckie`
2.  run `dts code editor`

**Comment by frank-qcd-qk** [comment]
Hi @sjev I have the same environment as you described. Can you provide me a bit more with your docker environment setup? it could be because you are running it inside a docker environment.

**Comment by sjev** [comment]
Sure, here is the whole docker file:

``` docker

FROM ubuntu:22.04

ARG USERNAME=dev
ARG UID
ARG GID

# Check for mandatory build arguments
RUN : "${UID:?Build argument needs to be set and non-empty.}" && \
    : "${GID:?Build argument needs to be set and non-empty.}" && \
    : "${USERNAME}:?Build argument needs to be set and non-empty.}"

# Create the user
RUN groupadd --gid $GID $USERNAME \
    && useradd --uid $UID --gid $GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME


# install packages
RUN apt-get install -y \
    locales \
    mc \
    tree \
    git \
    make \
    wget \
    curl \
    python3-pip

# set locale
RUN export LC_ALL=en_US.UTF-8
RUN export LANG=en_US.UTF-8
RUN locale-gen en_US.UTF-8

RUN pip install --upgrade pip

# install docker
RUN groupadd -g 998 docker
RUN usermod -aG docker ${USERNAME}
RUN curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh


USER ${USERNAME}
RUN echo 'export PS1="🦆  \[\033[1;36m\]\h \[\e[33m\]\W\[\e[m\] \[\033[1;36m\]# \[\033[0m\]"' >> ~/.bashrc

ENV PATH="${PATH}:/home/${USERNAME}/.local/bin"

WORKDIR /home/${USERNAME}



# setup folders for saving vscode extensions
# https://code.visualstudio.com/remote/advancedcontainers/avoid-extension-reinstalls
RUN mkdir -p /home/$USERNAME/.vscode-server/extensions \
    /home/$USERNAME/.vscode-server-insiders/extensions \
    && chown -R $USERNAME \
    /home/$USERNAME/.vscode-server \
    /home/$USERNAME/.vscode-server-insiders


# build timestamp
USER root
RUN echo duckie >> /build_date.txt && \
    date >> /build_date.txt

USER ${USERNAME}
WORKDIR /home/${USERNAME}

# duckietown stuff
RUN pip3 install --user -U duckietown-shell
RUN dts --set-version daffy


```

**Comment by sjev** [comment]
> Hi @sjev I have the same environment as you described. Can you provide me a bit more with your docker environment setup? it could be because you are running it inside a docker environment.

I don't think it's a docker environment thing. It's just `os.getlogin()` throwing an exception. This happened on my host system, so I tried to reproduce it in a docker environment to make sure that it was not my host being messed up. Reproducing in docker ruled that out.  

P.S. I suggest adding `os.getlogin()` to the test suite.
